# Generated by Django 4.0.4 on 2022-11-25 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('intervetionObject', models.CharField(max_length=50)),
                ('intervetionType', models.CharField(max_length=50)),
                ('interventionDate', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KpiTracking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('LeakerKpi', models.CharField(max_length=50)),
                ('NumberOfLeak', models.IntegerField()),
                ('numWaterHyd', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('leakerStartTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('cityNumber', models.IntegerField()),
                ('stateNumber', models.IntegerField()),
                ('streets', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('coupon', models.IntegerField()),
                ('counter', models.IntegerField()),
                ('queue', models.IntegerField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pipes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pipeNumber', models.IntegerField()),
                ('pipeStreet', models.CharField(max_length=50)),
                ('valves', models.CharField(max_length=50)),
                ('pipeType', models.CharField(max_length=50)),
                ('pipeColor', models.CharField(max_length=50)),
                ('pipeAcces', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reportObject', models.CharField(max_length=50)),
                ('senderName', models.CharField(max_length=50)),
                ('senderType', models.CharField(max_length=50)),
                ('reportDate', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sensorNumber', models.IntegerField()),
                ('sensorType', models.CharField(max_length=50)),
                ('sensorCoordinates', models.IntegerField()),
                ('sensorDetectionLength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('zoneCity', models.CharField(max_length=50)),
                ('zoneColor', models.CharField(max_length=50)),
                ('zoneCoordinates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='profile2.png', null=True, upload_to='profile_pics')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.CharField(blank=True, default='Male', max_length=200)),
                ('language', models.CharField(blank=True, default='English', max_length=200, null=True)),
                ('title', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('user_phone', models.CharField(blank=True, default='0000000000', max_length=200, null=True)),
                ('cell_phone', models.CharField(blank=True, default='0000000000', max_length=200, null=True)),
                ('fax_number', models.CharField(blank=True, default='0000000000', max_length=200, null=True)),
                ('postal', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
