# Generated by Django 4.0.4 on 2022-11-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('interventionObject', models.CharField(max_length=50)),
                ('interventionType', models.CharField(max_length=50)),
                ('interventionDate', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='intervetionObject',
            new_name='clientNameContract',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='interventionDate',
            new_name='contractData',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='intervetionType',
        ),
    ]
